name: http_extensions
description: Base classes for building extensions for http package.
version: 0.1.2
homepage: https://github.com/aloisdeniel/http_extensions
author: aloisdeniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0+1
